"""Initial schema: orders, ceidg_data, research_results, biznesplans, process_logs

Revision ID: 1eb33bfe6725
Revises: 
Create Date: 2025-11-21 18:58:12.291323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb33bfe6725'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('podio_item_id', sa.String(length=50), nullable=False),
    sa.Column('podio_workspace_id', sa.String(length=50), nullable=True),
    sa.Column('podio_app_id', sa.String(length=50), nullable=True),
    sa.Column('nip', sa.String(length=10), nullable=False),
    sa.Column('imie_nazwisko', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('uslugi', sa.JSON(), nullable=True),
    sa.Column('planowany_dochod_roczny', sa.Integer(), nullable=True),
    sa.Column('dodatkowe_informacje', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'FETCHING_DATA', 'GENERATING', 'REVIEWING', 'REFINING', 'COMPLETED', 'FAILED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('current_phase', sa.String(length=100), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_celery_task_id'), 'orders', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_nip'), 'orders', ['nip'], unique=False)
    op.create_index(op.f('ix_orders_podio_item_id'), 'orders', ['podio_item_id'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('biznesplans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=True),
    sa.Column('current_section_index', sa.Integer(), nullable=True),
    sa.Column('total_sections', sa.Integer(), nullable=True),
    sa.Column('generator_logs', sa.JSON(), nullable=True),
    sa.Column('reviewer_logs', sa.JSON(), nullable=True),
    sa.Column('final_word_count', sa.Integer(), nullable=True),
    sa.Column('final_page_count', sa.Integer(), nullable=True),
    sa.Column('final_quality_score', sa.Integer(), nullable=True),
    sa.Column('final_issues', sa.JSON(), nullable=True),
    sa.Column('total_cost_usd', sa.Integer(), nullable=True),
    sa.Column('cache_hit_rate', sa.Integer(), nullable=True),
    sa.Column('generation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biznesplans_id'), 'biznesplans', ['id'], unique=False)
    op.create_index(op.f('ix_biznesplans_order_id'), 'biznesplans', ['order_id'], unique=True)
    op.create_table('ceidg_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('nip', sa.String(length=10), nullable=False),
    sa.Column('regon', sa.String(length=14), nullable=True),
    sa.Column('nazwa_firmy', sa.String(length=500), nullable=False),
    sa.Column('imie', sa.String(length=100), nullable=True),
    sa.Column('nazwisko', sa.String(length=100), nullable=True),
    sa.Column('adres_ulica', sa.String(length=255), nullable=True),
    sa.Column('adres_numer_budynku', sa.String(length=20), nullable=True),
    sa.Column('adres_numer_lokalu', sa.String(length=20), nullable=True),
    sa.Column('adres_kod_pocztowy', sa.String(length=10), nullable=True),
    sa.Column('adres_miejscowosc', sa.String(length=255), nullable=True),
    sa.Column('adres_gmina', sa.String(length=255), nullable=True),
    sa.Column('adres_powiat', sa.String(length=255), nullable=True),
    sa.Column('adres_wojewodztwo', sa.String(length=255), nullable=True),
    sa.Column('pkd_glowny', sa.String(length=10), nullable=True),
    sa.Column('pkd_glowny_nazwa', sa.String(length=500), nullable=True),
    sa.Column('pkd_pozostale', sa.JSON(), nullable=True),
    sa.Column('data_rozpoczecia_dzialalnosci', sa.String(length=20), nullable=True),
    sa.Column('data_zakonczenia_dzialalnosci', sa.String(length=20), nullable=True),
    sa.Column('status_wpisu', sa.String(length=50), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ceidg_data_id'), 'ceidg_data', ['id'], unique=False)
    op.create_index(op.f('ix_ceidg_data_nip'), 'ceidg_data', ['nip'], unique=False)
    op.create_index(op.f('ix_ceidg_data_order_id'), 'ceidg_data', ['order_id'], unique=True)
    op.create_table('process_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='loglevel'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_logs_created_at'), 'process_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_process_logs_id'), 'process_logs', ['id'], unique=False)
    op.create_index(op.f('ix_process_logs_order_id'), 'process_logs', ['order_id'], unique=False)
    op.create_table('research_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('market_data', sa.JSON(), nullable=True),
    sa.Column('swot_data', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('research_method', sa.String(length=50), nullable=True),
    sa.Column('research_queries', sa.JSON(), nullable=True),
    sa.Column('research_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('source_quality_score', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('researched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_results_id'), 'research_results', ['id'], unique=False)
    op.create_index(op.f('ix_research_results_order_id'), 'research_results', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_results_order_id'), table_name='research_results')
    op.drop_index(op.f('ix_research_results_id'), table_name='research_results')
    op.drop_table('research_results')
    op.drop_index(op.f('ix_process_logs_order_id'), table_name='process_logs')
    op.drop_index(op.f('ix_process_logs_id'), table_name='process_logs')
    op.drop_index(op.f('ix_process_logs_created_at'), table_name='process_logs')
    op.drop_table('process_logs')
    op.drop_index(op.f('ix_ceidg_data_order_id'), table_name='ceidg_data')
    op.drop_index(op.f('ix_ceidg_data_nip'), table_name='ceidg_data')
    op.drop_index(op.f('ix_ceidg_data_id'), table_name='ceidg_data')
    op.drop_table('ceidg_data')
    op.drop_index(op.f('ix_biznesplans_order_id'), table_name='biznesplans')
    op.drop_index(op.f('ix_biznesplans_id'), table_name='biznesplans')
    op.drop_table('biznesplans')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_podio_item_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_nip'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_celery_task_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
